---
- name: Install
  hosts: servera
  become: yes
  vars:
    package: policycoreutils
    mount_place: /data/speci
    type_fs: "ext4"
  roles:  
    - package
    - journald
    - raid
    - fstab
