- name: Journald Permanent
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#storage'
    line: storage=persistent
  register: state


- name: Reset journal
  service:
    name: systemd-journald.service
    state: restarted
  when: state.changed
  notify:
    - Journal reset 
